language: android

jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - sys-img-armeabi-v7a-android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew

script:
  - ./gradlew clean build

deploy:
  - provider: releases
    token: $GITHUB_API_KEY
    file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
    skip_cleanup: true
    name: dev-build-$TRAVIS_TAG
    release_notes: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
    prerelease: true
    overwrite: true
    target_commitish: $TRAVIS_COMMIT
    on:
      tags: true

  - provider: script
    script: ./gradlew :clean :conversation-starter:assembleRelease :conversation-starter:bintrayUpload
    skip_cleanup: true
    on:
      tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs